"""PRD §14 운영 상수."""

# 수집 주기
SCHEDULER_HOUR = "*"
SCHEDULER_MINUTE = 0

# 동시성
FEED_FETCH_CONCURRENCY = 5
FEED_FETCH_TIMEOUT_SECONDS = 30
EXTRACTOR_TIMEOUT_SECONDS = 20

# LLM
LLM_SUBPROCESS_TIMEOUT_SECONDS = 120
LLM_BACKOFF_MAX_RETRIES = 3
LLM_BACKOFF_DELAYS = (2, 4, 8)  # seconds
LLM_PARALLEL_CONCURRENCY = 3   # 동시에 실행할 claude -p 프로세스 수

# Wiki 재구성
WIKI_INPUT_MAX_CHARS = 100_000
WIKI_INITIAL_BUILD_ARTICLE_COUNT = 20
WIKI_INCREMENTAL_CONTEXT_COUNT = 10

# 카테고리
CATEGORY_MAX_DEPTH = 2  # root → leaf

# 파일 경로
DB_PATH = "./data/rss-wiki.db"
LOG_FILE_PATH = "./data/logs/rss-wiki.log"
LOG_MAX_ENTRIES = 200

# 서버
BIND_HOST = "127.0.0.1"
BIND_PORT = 8000

# LLM 출력 언어
LLM_OUTPUT_LANGUAGE = "한국어"
